<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>html</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~H</string>
	<key>name</key>
	<string>㎆ HTML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(?x)(?:^\s+)?(&lt;)((?i:style))\b(?![^&gt;]*/&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.mb</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.style.mb</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.mb</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?x)(&lt;/)((?i:style))(&gt;)(?:\s*\n)?</string>
			<key>name</key>
			<string>source.css.embedded.mb</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?x)(&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.mb</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?x)(?=&lt;/(?i:style))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.css</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?x)(?:^\s+)?(&lt;)((?i:script))\b(?![^&gt;]*/&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.mb</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.script.mb</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?x)(?&lt;=&lt;/(script|SCRIPT))(&gt;)(?:\s*\n)?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.mb</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.js.embedded.mb</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?x)(?&lt;!&lt;/(?:script|SCRIPT))(&gt;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.mb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.script.mb</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?x)(&lt;/)((?i:script))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.js</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?x)(//).*?((?=&lt;/script)|$\n?)</string>
							<key>name</key>
							<string>comment.line.double-slash.js</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?x)/\*</string>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.js</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?x)\*/|(?=&lt;/script)</string>
							<key>name</key>
							<string>comment.block.js</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?x)(&lt;/?)([a-zA-Z0-9:]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.mb</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.other.mb</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?x)(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.mb</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.other.mb</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?x)&lt;!--</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.mb</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?x)--\s*&gt;</string>
			<key>name</key>
			<string>comment.block.mb</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?x)--</string>
					<key>name</key>
					<string>invalid.illegal.bad-comments-or-CDATA.mb</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#entities</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>entities</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.mb</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.mb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)(&amp;) # 1
					([a-zA-Z0-9]+|\#[0-9]+|\#x[0-9a-fA-F]+) # 2
					(;) # 3
					</string>
					<key>name</key>
					<string>constant.character.entity.mb</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x)&amp;</string>
					<key>name</key>
					<string>invalid.illegal.bad-ampersand.mb</string>
				</dict>
			</array>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>begin</key>
			<string>(?x)&quot;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.mb</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?x)&quot;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.mb</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.mb</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>string-single-quoted</key>
		<dict>
			<key>begin</key>
			<string>(?x)'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.mb</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?x)'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.mb</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.mb</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>tag-generic-attribute</key>
		<dict>
			<key>match</key>
			<string>(?x)\b([a-zA-Z\-:]+)</string>
			<key>name</key>
			<string>entity.other.attribute-name.mb</string>
		</dict>
		<key>tag-stuff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-generic-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.mb</string>
	<key>uuid</key>
	<string>110C54F5-F865-4EF7-88BC-7B3F204F5325</string>
</dict>
</plist>
